import { StyleSheet } from 'react-native';

export const HomeScreenStyles = StyleSheet.create({
  scrollContainer: {
    padding: 24,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  foodImage: {
    width: 180,
    height: 180,
    marginTop: 24,
    marginBottom: 8,
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 1.5,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
    marginBottom: 10,
  },
  saleButtonWrapper: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 16,
  },
  saleButton: {
    width: '70%',
    alignSelf: 'center',
    borderRadius: 20,
    paddingVertical: 16,
    marginTop: 0,
    marginBottom: 0,
    elevation: 8,
    shadowColor: '#8D5524',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    borderWidth: 2,
  },
  testButton: {
    width: '60%',
    alignSelf: 'center',
    borderRadius: 16,
    marginTop: 12,
    paddingVertical: 14,
    elevation: 4,
    shadowColor: '#A67C52',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    maxHeight: 50,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBox: {
    width: 320,
    borderRadius: 18,
    padding: 24,
    borderWidth: 2,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 12,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 12,
    letterSpacing: 1.1,
  },
  modalOrderText: {
    fontSize: 16,
    marginBottom: 8,
  },
  modalButton: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 10,
    alignItems: 'center',
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1.1,
  },
  todaysSalesContainer: {
    width: '100%',
    marginTop: 20,
    padding: 16,
    backgroundColor: '#FFF7ED',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#A67C52',
  },
  todaysSalesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  todaysSalesTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    letterSpacing: 1.2,
    flex: 1,
  },
  refreshButton: {
    backgroundColor: '#A67C52',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8D5524',
  },
  refreshButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  salesNumbersContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  salesNumberCard: {
    width: '48%',
    backgroundColor: '#F3E1C7',
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2B07A',
  },
  salesNumberLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7C5E3C',
    marginBottom: 4,
  },
  salesNumberValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#5C4032',
  },
  chartContainer: {
    width: '100%',
    alignItems: 'center',
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  chartLegend: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 12,
    flexWrap: 'wrap',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 8,
    marginVertical: 4,
  },
  legendColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  legendText: {
    fontSize: 12,
    fontWeight: '500',
  },
  noDataContainer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  noDataText: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  noDataSubtext: {
    fontSize: 14,
    textAlign: 'center',
    fontStyle: 'italic',
  },
}); 